version: '3.8'

services:
  # Contenedor para la aplicación Flask
  app:
    build:
      context: ./PROYECTO_PI  # Carpeta donde se encuentra tu proyecto
      dockerfile: Dockerfile  # Asegúrate de tener un Dockerfile en la raíz de tu proyecto
    container_name: undersound_app
    environment:
      - DB_HOST=db  # Nombre del contenedor de la base de datos (reemplaza localhost por db)
      - DB_USER=root
      - DB_PASSWORD=123456ABC
      - DB_NAME=undersound
    volumes:
      - ./PROYECTO_PI:/app  # Montar la carpeta del proyecto al contenedor
    ports:
      - "5000:5000"  # Exponer el puerto 5000 para acceder a la app Flask
    networks:
      - app-network  # Red para la aplicación Flask

  # Contenedor para la base de datos MySQL
  db:
    image: mysql:5.7
    container_name: undersounds_db
    environment:
      - MYSQL_ROOT_PASSWORD=123456ABC
      - MYSQL_DATABASE=undersound
    volumes:
      - db_data:/var/lib/mysql  # Persistencia de datos de MySQL
    ports:
      - "3306:3306"  # Exponer el puerto 3306 para la base de datos
    networks:
      - app-network  # Red para la base de datos MySQL

# Volúmenes para persistir los datos de la base de datos
volumes:
  db_data:
    driver: local

# Redes
networks:
  app-network:
    driver: bridge  # Red interna para la comunicación entre los contenedores


