
services:
  # Contenedor para la aplicación Flask
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: undersound_app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456ABC
      - DB_NAME=undersound
      - DB_PORT=3306
    ports:
      - "5000:5000"
    networks:
      - app_network
    restart: always

  # Contenedor para la base de datos MySQL
  db:
    image: mysql:8.0
    container_name: undersounds_db
    environment:
      - MYSQL_ROOT_PASSWORD=123456ABC
      - MYSQL_DATABASE=undersound
    volumes:
      - db_data:/var/lib/mysql
      - ./db/undersoundBaseDatos.sql:/docker-entrypoint-initdb.d/undersoundBaseDatos.sql
    ports:
      - "3307:3306"
    expose:
      - "3306"
    networks:
      - app_network

# Volúmenes para persistir los datos de la base de datos
volumes:
  db_data:
    driver: local

# Redes
networks:
  app_network:
    driver: bridge
    name: app_network